[project]
name = "community-beszel"
version = "0.3.1"
description = "Ansible community collection for Beszel."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible-core==2.18.7",
    "pocketbase>=0.15.0",
]

[dependency-groups]
dev = [
    "antsibull-changelog[toml]==0.34.0",
    "pre-commit==4.2.0",
    "ruff>=0.12.11",
    {include-group = "lint"},
    {include-group = "test"},
]
lint = [
    "ansible-lint==25.8.1"
]
test = [
    "molecule==25.7.0",
    "molecule-plugins[docker]==23.7.0",
    "jmespath==1.0.1"
]
