---
services:
  beszel:
    image: ghcr.io/henrygd/beszel/beszel:0.18.2
    container_name: beszel
    restart: unless-stopped
    environment:
      - USER_EMAIL=molecule@example.com
      - USER_PASSWORD=molecule
    networks:
      - beszel
    ports:
      - 8090:8090
    volumes:
      - beszel_data:/beszel_data

volumes:
  beszel_data:

networks:
  beszel:
